### ISSUE TITLE
Zmień nazwe repo

### ISSUE THREAD

**Issue by Pawi1** [JablonskiJakubb/JablonskiJakubb.github.io#1]
masz inny nick i te repo bez sensu się tak nazywa
zmień nazwe tego repo na "jablonskiJakubb.github.io"

**Comment by Pawi1** [comment]
my nie możemy jakby co

**Comment by PerzotProgrammer** [comment]
JABŁON TY CH ZMIEŃ NAZWĘ REPO!!!

**Comment by Pawi1** [comment]
??????????
